version: 0.2

env:
  variables:
    key: "STREAM"
  # key: "value"
  #parameter-store:
  # key: "value"
  # key: "value"
#git-credential-helper: yes

phases:
  install:
    runtime-versions:
      nodejs: 10
  #install:
  #If you use the Ubuntu standard image 2.0 or later, you must specify runtime-versions.
  #If you specify runtime-versions and use an image other than Ubuntu standard image 2.0, the build fails.
  #runtime-versions:
  # name: version
  # name: version
  #commands:
  # - command
  # - command
  #pre_build:
  #commands:
  # - command
  # - command
  build:
    commands:
      - node --version
      - chmod +x scripts/*.sh
      - mkdir .build
      - mkdir .tmp
      - scripts/package.sh $STREAM $CODEBUILD_RESOLVED_SOURCE_VERSION
  post_build:
    commands:
      - echo Build completed on `date`
      - ls -al .build/*.zip
artifacts:
  files:
    - '*.zip'
  base-directory: .build
    # - command
#post_build:
#commands:
# - command
# - command
#artifacts:
#files:
# - location
# - location
#name: $(date +%Y-%m-%d)
#discard-paths: yes
#base-directory: location
#cache:
#paths:
# - paths